### ISSUE TITLE
Add individual region configurations

### ISSUE THREAD

**Issue by Th3Shadowbroker** [Th3Shadowbroker/OuroborosMines#2]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A possibility to set individual cooldowns for different mines using a config file.
See [this thread](https://www.spigotmc.org/threads/ouroboros-mines.401636/) for reference!

**ToDo**
- [x] Update dependencies
- [x] Check WorldGuard for region-id handling
- [x] Build working prototype
- [x] Create complete implementation based on prototype
- [x] Add command to trigger config generation to keep obsolete configurations from being generated
- [x] Final polish
